#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-multilib
Version  : 1.2
Release  : 26
URL      : http://pypi.debian.net/python-multilib/python-multilib-1.2.tar.gz
Source0  : http://pypi.debian.net/python-multilib/python-multilib-1.2.tar.gz
Summary  : module for determining if a package is multilib
Group    : Development/Tools
License  : GPL-2.0
Requires: python-multilib-license = %{version}-%{release}
Requires: python-multilib-python = %{version}-%{release}
Requires: python-multilib-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-legacypython
BuildRequires : six

%description
# python-multilib
A Python library for determining if a package is multilib or not

%package license
Summary: license components for the python-multilib package.
Group: Default

%description license
license components for the python-multilib package.


%package python
Summary: python components for the python-multilib package.
Group: Default
Requires: python-multilib-python3 = %{version}-%{release}

%description python
python components for the python-multilib package.


%package python3
Summary: python3 components for the python-multilib package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-multilib package.


%prep
%setup -q -n python-multilib-1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554327205
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-multilib
cp LICENSE %{buildroot}/usr/share/package-licenses/python-multilib/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-multilib/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
