#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-multilib
Version  : 1.2
Release  : 1
URL      : https://pypi.python.org/packages/b3/80/4634cb9962b2fcfb37c9f80c9a99a9e8dc2b0c0db7f6d055cb31d8b5dedf/python-multilib-1.2.tar.gz
Source0  : https://pypi.python.org/packages/b3/80/4634cb9962b2fcfb37c9f80c9a99a9e8dc2b0c0db7f6d055cb31d8b5dedf/python-multilib-1.2.tar.gz
Summary  : module for determining if a package is multilib
Group    : Development/Tools
License  : GPL-2.0
Requires: python-multilib-python
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
# python-multilib
A Python library for determining if a package is multilib or not

%package python
Summary: python components for the python-multilib package.
Group: Default

%description python
python components for the python-multilib package.


%prep
%setup -q -n python-multilib-1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1499652119
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1499652119
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
